FROM node:21-alpine

WORKDIR /usr/src/app

COPY svelte.config.js ./
COPY vite.config.js ./
COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 4173

CMD [ "npm", "run", "preview" ]